### ISSUE TITLE
Failure of two tests

### ISSUE THREAD

**Issue by zabibbo** [Tudat/PropagationOptimizationAssignments#1]
While I was running the newly implemented tests, two of them failed. There are no further information on the errors aside from what I attach to this issue.

Operating system: Windows 10
Qt version: Qt 5.13.2
I don't know where I can check what Cmake version I have, but I suppose that it is the latest release.

[errorCMAKE.txt](https://github.com/Tudat/tudatBundle/files/4176624/errorCMAKE.txt)

**Comment by DominicDirkx** [comment]
Hi Benedetta,

Thanks for doing the update so quickly. We are currently tracking this issue here:

https://github.com/Tudat/tudat/issues/610

Please post your log files that are requested in that issue there, and well have a look,

Best,

Dominic
