### ISSUE TITLE
Pagmo installation failing

### ISSUE THREAD

**Issue by callejon97** [Tudat/PropagationOptimizationAssignments#2]
While trying to build pagmo with the command `cmake.exe --build . --target all -- -j12`, the following error arises: 

> [ 97%] Built target test_ArcwiseEnvironmentEstimationmingw32-make.exe: *** >[Makefile:140: all] Error 2
>21:26:20: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
>Error while building/deploying project TudatBundle (kit: Desktop Qt 5.12.5 MinGW 64-bit)
>When executing step "CMake Build". 

Previously, I did try to run the unit tests with the command `"cmake.exe --build . --target test "` and `"cmake.exe --build . --target test -j12"` and the output code was: 

> 77% tests passed, 78 tests failed out of 333
Total Test time (real) = 630.97 secThe following tests FAILED:
 2 - ackley (Not Run)
 3 - algorithm (Not Run)
 4 - algorithm_type_traits (Not Run)
 5 - archipelago (Not Run)
 6 - archipelago_torture_test (Not Run)
 7 - base_bgl_topology (Not Run)
 8 - base_sr_policy (Not Run)
 9 - bee_colony (Not Run)
 10 - cec2006 (Not Run)
 11 - cec2009 (Not Run)
 12 - compass_search (Not Run)
 13 - constrained (Not Run)
 14 - custom_comparisons (Not Run)
 15 - cstrs_self_adaptive (Not Run)
 16 - de (Not Run)
 17 - de1220 (Not Run)
 18 - decompose (Not Run)
 19 - discrepancy (Not Run)
 20 - dtlz (Not Run)
 21 - fair_replace (Not Run)
 22 - fully_connected (Not Run)
 23 - gwo (Not Run)
 24 - gaco (Not Run)
 25 - generic (Not Run)
 26 - golomb_ruler (Not Run)
 27 - gradients_and_hessians (Not Run)
 28 - griewank (Not Run)
 29 - hypervolume (Not Run)
 30 - hock_schittkowsky_71 (Not Run)
 31 - inventory (Not Run)
 32 - lennard_jones (Not Run)
 33 - migration_torture_test (Not Run)
 34 - minlp_rastrigin (Not Run)
 35 - ihs (Not Run)
 36 - io (Not Run)
 37 - island (Not Run)
 38 - island_torture (Not Run)
 39 - luksan_vlcek1 (Not Run)
 40 - mbh (Not Run)
 41 - moead (Not Run)
 42 - multi_objective (Not Run)
 43 - nsga2 (Not Run)
 44 - nspso (Not Run)
 45 - population (Not Run)
 46 - problem (Not Run)
 47 - problem_type_traits (Not Run)
 48 - pso (Not Run)
 49 - pso_gen (Not Run)
 50 - r_policy (Not Run)
 51 - rastrigin (Not Run)
 52 - ring (Not Run)
 53 - rng (Not Run)
 54 - rng_serialization (Not Run)
 55 - rosenbrock (Not Run)
 56 - s_policy (Not Run)
 57 - sade (Not Run)
 58 - simulated_annealing (Not Run)
 59 - sga (Not Run)
 60 - schwefel (Not Run)
 61 - sea (Not Run)
 62 - select_best (Not Run)
 63 - threading (Not Run)
 64 - thread_island (Not Run)
 65 - topology (Not Run)
 66 - translate (Not Run)
 67 - type_traits (Not Run)
 68 - unconnected (Not Run)
 69 - unconstrain (Not Run)
 70 - wfg (Not Run)
 71 - zdt (Not Run)
 72 - cmaes (Not Run)
 73 - eigen3_serialization (Not Run)
 74 - xnes (Not Run)
 75 - getting_started (Not Run)
 76 - nsga2_example (Not Run)
 77 - problem_basic (Not Run)
 78 - problem_basic_gh (Not Run)
 79 - problem_basic_s (Not Run)
Errors while running CTest
mingw32-make.exe: *** [Makefile:72: test] Error 8
20:39:38: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop Qt 5.12.5 MinGW 64-bit)
When executing step "CMake Build"

Operative system: W10 (unfortunately didn't had time to install linux)
Qt version: Qt 5.12.5

**Comment by DominicDirkx** [comment]
Hi Miguel,

Could  you please post the full compilation output (in a text file) you get when removing the 'test' and '-j12' command? 

Best,

Dominic

**Comment by callejon97** [comment]
Hi Dominic, 

Thank you for the quick answer. `Build: cmake.exe --build . --target all` has finished ok. Compilation output is attached. `cmake.exe --build . --target test` also: 100% test passed!! 

[installationPagmo1.txt](https://github.com/Tudat/PropagationOptimizationAssignments/files/4392699/installationPagmo1.txt)
[installationPagmo2.txt](https://github.com/Tudat/PropagationOptimizationAssignments/files/4392733/installationPagmo2.txt)

However, do you know what might be the reasons why yesterday it did not work?

Best, 
Miguel

**Comment by DominicDirkx** [comment]
My best guess is that the multi-core compilation ran into some issues, with some things not yet being compiled, while some thread 'thought' they would be. Glad to see that it works now!
